/**
 * MemOS — Universal memory layer for AI agents.
 *
 * Core type definitions. Every interface and type in the system
 * is defined here to provide a single source of truth for the
 * data model across modules.
 *
 * @module @memos/types
 */

// ---------------------------------------------------------------------------
// Memory Nodes
// ---------------------------------------------------------------------------

/**
 * Semantic category for a memory node.
 *
 * - `fact`          — A discrete piece of information.
 * - `preference`    — A user or agent preference.
 * - `context`       — Conversational or situational context.
 * - `relationship`  — An observed relationship between entities.
 * - `entity`        — A named entity (person, place, thing).
 * - `custom`        — Application-defined type.
 */
export type MemoryType =
  | "fact"
  | "preference"
  | "context"
  | "relationship"
  | "entity"
  | "custom";

/**
 * Provenance source for a memory node.
 *
 * - `user_input`     — Stated directly by the user. Highest trust.
 * - `agent_inferred` — Inferred by an agent from context.
 * - `external_data`  — Imported from an external source.
 * - `system`         — Generated by the system itself.
 */
export type MemorySource =
  | "user_input"
  | "agent_inferred"
  | "external_data"
  | "system";

/**
 * Default trust score for each provenance source.
 */
export const DEFAULT_TRUST_SCORES: Record<MemorySource, number> = {
  user_input: 1.0,
  agent_inferred: 0.7,
  external_data: 0.5,
  system: 0.3,
};

/**
 * A single unit of memory stored in the graph.
 */
export interface MemoryNode {
  /** Globally unique identifier (UUID v4). */
  id: string;
  /** Raw text content of the memory. */
  content: string;
  /** Extractive summary (auto-generated if not supplied). */
  summary: string;
  /** Semantic type of this memory. */
  type: MemoryType;
  /** Arbitrary metadata bag. Must be JSON-serialisable. */
  metadata: Record<string, unknown>;
  /** Importance score in [0, 1]. Auto-computed from access patterns. */
  importance: number;
  /** Creation timestamp (Unix ms). */
  createdAt: number;
  /** Last-modified timestamp (Unix ms). */
  updatedAt: number;
  /** Number of times this node has been retrieved. */
  accessCount: number;
  /** Timestamp of last access (Unix ms). */
  lastAccessed: number;
  /** Custom tags for categorisation. */
  tags: string[];
  /** TTL expiration as Unix timestamp (seconds). null = no expiration. */
  expiresAt: number | null;
  /** Namespace for grouping memories (experimental). */
  namespace: string;
  /**
   * Temporal validity start (Unix ms). When set, the memory is
   * considered "active" from this point in time. null = always valid.
   */
  validFrom: number | null;
  /**
   * Temporal validity end (Unix ms). When set, the memory becomes
   * "historical" (excluded from default search) after this time.
   * null = no expiry. Superseded memories keep their validTo so the
   * history is queryable via `searchTemporal`.
   */
  validTo: number | null;
  /**
   * Where this memory originated. Used for provenance and trust
   * scoring.
   * - `user_input`     — Stated directly by the user. Highest trust.
   * - `agent_inferred` — Inferred by an agent from context. Lower trust.
   * - `external_data`  — Imported from an external source (API, file, etc.).
   * - `system`         — Generated by the system itself.
   */
  source: MemorySource;
  /**
   * Trust score in [0, 1]. Influences retrieval ranking. Starts at
   * 1.0 for `user_input`, 0.7 for `agent_inferred`, 0.5 for
   * `external_data`, 0.3 for `system`. Can be manually adjusted via
   * `memos.setTrust()`.
   */
  trustScore: number;
}

/**
 * Partial input accepted when creating a new memory.
 * Only `content` is required; everything else has defaults.
 */
export interface CreateMemoryInput {
  content: string;
  type?: MemoryType;
  metadata?: Record<string, unknown>;
  summary?: string;
  importance?: number;
  /** TTL in seconds from now. */
  ttl?: number;
  /** Custom tags. */
  tags?: string[];
  /** Namespace (experimental). */
  namespace?: string;
  /** Temporal validity start (Unix ms). null = always valid. */
  validFrom?: number | null;
  /** Temporal validity end (Unix ms). null = no expiry. */
  validTo?: number | null;
  /** Provenance source. Default: `user_input`. */
  source?: MemorySource;
  /** Trust score [0, 1]. Overrides the default for the chosen source. */
  trustScore?: number;
  /**
   * When true, apply the Hermes-style retain pre-filter (v1.6.26) before
   * writing: low-signal content (acknowledgements, chit-chat, near-empty
   * text) is skipped so long-term memory isn't flooded with noise that would
   * later bloat context-packs. Default: false (write always).
   */
  filterRetain?: boolean;
}

/**
 * Partial update for an existing memory node.
 */
export interface UpdateMemoryInput {
  content?: string;
  summary?: string;
  type?: MemoryType;
  metadata?: Record<string, unknown>;
  importance?: number;
  tags?: string[];
  namespace?: string;
  /** Temporal validity start (Unix ms). */
  validFrom?: number | null;
  /** Temporal validity end (Unix ms). */
  validTo?: number | null;
  /** Provenance source. */
  source?: MemorySource;
  /** Trust score [0, 1]. */
  trustScore?: number;
}

// ---------------------------------------------------------------------------
// Memory Edges
// ---------------------------------------------------------------------------

/**
 * Semantic relation between two memory nodes.
 *
 * - `relates_to`     — General association.
 * - `contradicts`    — The target contradicts the source.
 * - `supports`       — The target supports the source.
 * - `derived_from`   — The source was derived from the target.
 * - `part_of`        — The source is a part of the target.
 * - `custom`         — Application-defined relation.
 */
export type EdgeRelation =
  | "relates_to"
  | "contradicts"
  | "supports"
  | "derived_from"
  | "part_of"
  | "temporal_precedes"
  | "custom";

/**
 * A directed, weighted edge connecting two memory nodes.
 */
export interface MemoryEdge {
  /** Globally unique identifier (UUID v4). */
  id: string;
  /** Source node ID. */
  sourceId: string;
  /** Target node ID. */
  targetId: string;
  /** Semantic relation label. */
  relation: EdgeRelation;
  /** Edge weight in [0, 1]. */
  weight: number;
  /** Arbitrary metadata bag. */
  metadata: Record<string, unknown>;
  /** Creation timestamp (Unix ms). */
  createdAt: number;
}

/**
 * Input for creating a new edge.
 */
export interface CreateEdgeInput {
  sourceId: string;
  targetId: string;
  relation?: EdgeRelation;
  weight?: number;
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Search & Query
// ---------------------------------------------------------------------------

/**
 * Filter criteria for searching memories.
 */
export interface SearchFilter {
  /** Full-text search query. */
  query?: string;
  /** Filter by memory type. */
  type?: MemoryType;
  /** Minimum importance threshold [0, 1]. */
  minImportance?: number;
  /** Maximum importance threshold [0, 1]. */
  maxImportance?: number;
  /** Metadata key-value filter. */
  metadata?: Record<string, unknown>;
  /** Limit the number of results. */
  limit?: number;
  /** Offset for pagination. */
  offset?: number;
  /** Sort field. */
  sortBy?:
    | "importance"
    | "createdAt"
    | "updatedAt"
    | "accessCount"
    | "relevance"
    | "trustScore";
  /** Sort direction. */
  sortOrder?: "asc" | "desc";
  /** Filter by tags (AND logic — node must have ALL specified tags). */
  tags?: string[];
  /** Filter by namespace (experimental). */
  namespace?: string;
  /** Filter by provenance source. */
  source?: MemorySource;
  /** Minimum trust score [0, 1]. */
  minTrustScore?: number;
  /**
   * When true (default), exclude memories whose `validTo` is in the
   * past (i.e. historical/superseded memories). Set to false to
   * include historical memories.
   */
  includeHistorical?: boolean;
  /**
   * When set, only return memories that were valid at this point in
   * time (Unix ms). A memory is "valid at time T" if:
   *   (validFrom is null OR validFrom <= T) AND
   *   (validTo is null OR validTo >= T)
   */
  validAt?: number;
}

/**
 * AI Trio context pack — a token-budgeted, ranked, namespace-filtered
 * slice of memory intended to be folded into an LLM prompt by Guardian.
 *
 * See `docs/ai-trio-contracts.md` for the full contract.
 */
export interface ContextPackItem {
  id: string;
  content: string;
  summary: string;
  score: number;
  scores?: {
    keyword?: number;
    semantic?: number;
    hybrid?: number;
  };
  trust: string;
  source: string;
  tags: string[];
  updatedAt: string;
}

export interface ContextPack {
  schema: "ai-trio.memos.context-pack.v1";
  query: string;
  namespace: string;
  tokenBudget: number;
  items: ContextPackItem[];
}

/**
 * A memory node bundled with its relevance score after a search.
 */
export interface ScoredMemory {
  node: MemoryNode;
  /** Relevance score returned by the search algorithm. */
  score: number;
  /** Optional score breakdown for hybrid retrieval. */
  scores?: {
    keyword?: number;
    semantic?: number;
    hybrid?: number;
  };
}

// ---------------------------------------------------------------------------
// Embeddings
// ---------------------------------------------------------------------------

export type EmbeddingVector = number[];

export interface EmbeddingProvider {
  /** Stable provider identifier, e.g. "local-hash" or "ollama". */
  id: string;
  /** Human-readable embedding model name. */
  model: string;
  /** Expected vector dimensionality. */
  dimensions: number;
  /** Generate a normalized embedding vector for a text input. */
  embed(text: string): Promise<EmbeddingVector>;
  /**
   * Optional batch embedding. If the provider can batch, override this to
   * amortize network round-trips. Default implementation calls `embed` for
   * each text in order. The returned vectors must be in the same order as
   * the input `texts` array.
   */
  batchEmbed?(texts: string[]): Promise<EmbeddingVector[]>;
}

export type EmbeddingProviderKind =
  | "local-hash"
  | "ollama"
  | "openai-compatible"
  | "voyage"
  | "cohere"
  | "fastembed";

export interface EmbeddingConfig {
  /** Enables embedding generation. Defaults to true when semantic search is enabled. */
  enabled?: boolean;
  /** Built-in provider kind, or a custom provider implementation. */
  provider?: EmbeddingProviderKind | EmbeddingProvider;
  /** Provider model name. */
  model?: string;
  /** Embedding vector dimensions. */
  dimensions?: number;
  /** Base URL for Ollama or OpenAI-compatible embedding endpoints. */
  baseUrl?: string;
  /** API key for OpenAI-compatible embedding endpoints. */
  apiKey?: string;
}

export interface EmbeddingRecordInfo {
  model: string;
  dimensions: number;
  updatedAt: number;
}

/**
 * Per-node embedding pipeline status. `pending` means the node has been
 * stored but its embedding has not been computed yet. `ready` means the
 * persisted vector is fresh for the current provider/model. `failed`
 * means the most recent attempt gave up after retries.
 */
export type EmbeddingNodeStatus = "pending" | "queued" | "running" | "ready" | "failed";

/** Lightweight status snapshot returned by `memos.embeddingStatus()`. */
export interface EmbeddingNodeStatusInfo {
  nodeId: string;
  status: EmbeddingNodeStatus;
  attempts: number;
  lastError: string | null;
  updatedAt: number;
}

/** Aggregate status returned by `memos.embeddingStatus()` (no args). */
export interface EmbeddingQueueStatus {
  pending: number;
  running: number;
  total: number;
  nodes: EmbeddingNodeStatusInfo[];
}

/**
 * Configuration for the background embedding queue. All fields are
 * optional; sensible defaults are used when omitted.
 */
export interface EmbeddingQueueConfig {
  /** Max concurrent in-flight embed calls. Default 2. */
  concurrency?: number;
  /** Max buffered jobs before `enqueue` throws. Default 10000. */
  maxQueueSize?: number;
  /** Max retry attempts per job before marking it failed. Default 3. */
  maxRetries?: number;
  /** Base backoff in ms; retries use exponential backoff. Default 250. */
  retryBackoffMs?: number;
  /**
   * If true, `store()` waits for the embedding to complete before
   * returning. Default false — background mode. Tests and the CLI
   * `memos flush-embeddings` command benefit from this being false.
   */
  synchronous?: boolean;
}

// ---------------------------------------------------------------------------
// Graph
// ---------------------------------------------------------------------------

/**
 * Full in-memory graph snapshot.
 */
export interface GraphSnapshot {
  nodes: MemoryNode[];
  edges: MemoryEdge[];
}

// ---------------------------------------------------------------------------
// Storage Adapter Interface
// ---------------------------------------------------------------------------

/**
 * Backend-agnostic storage contract.
 *
 * Any persistence backend (SQLite, Postgres, Redis, Qdrant …) must
 * implement this interface. The core engine only depends on this
 * contract, never on a concrete backend.
 */
export interface StorageAdapter {
  /** Initialise tables / indices / connections. Called once at startup. */
  init(): Promise<void>;

  /** Persist a new memory node. Returns the created node. */
  saveNode(node: MemoryNode): Promise<MemoryNode>;

  /** Retrieve a node by ID. Returns `null` when not found.
   *  Implementations should bump the access stats (access_count,
   *  last_accessed) on read. For side-effect-free reads, use `peekNode`. */
  getNode(id: string): Promise<MemoryNode | null>;

  /**
   * Side-effect-free variant of `getNode`. Does not increment
   * `access_count` or update `last_accessed`. Use for internal lookups
   * where the read is not a user-initiated retrieval — e.g. tag
   * updates, TTL changes, eviction candidate selection.
   */
  peekNode?(id: string): Promise<MemoryNode | null>;

  /**
   * Delete the single least-important node, where "least important" is
   * defined as lowest `importance` then oldest `last_accessed`.
   * Returns the id of the deleted node, or null if the table is empty.
   * Implementations may fall back to in-memory selection if SQL is
   * not appropriate.
   */
  evictLeastImportant?(): Promise<string | null>;

  /** Partially update a node. Returns the updated node. */
  updateNode(id: string, input: UpdateMemoryInput): Promise<MemoryNode | null>;

  /** Delete a node and all connected edges. */
  deleteNode(id: string): Promise<boolean>;

  /** Persist a new edge. Returns the created edge. */
  saveEdge(edge: MemoryEdge): Promise<MemoryEdge>;

  /**
   * Batch-insert multiple edges in a single transaction.
   * Falls back to individual saveEdge calls when not implemented.
   */
  saveEdgesBatch?(edges: MemoryEdge[]): Promise<MemoryEdge[]>;

  /** Retrieve an edge by ID. */
  getEdge(id: string): Promise<MemoryEdge | null>;

  /** Delete an edge by ID. */
  deleteEdge(id: string): Promise<boolean>;

  /** Query nodes with filters. */
  queryNodes(filter: SearchFilter): Promise<ScoredMemory[]>;

  /** Persist an embedding vector for a node. */
  saveEmbedding?(
    nodeId: string,
    vector: EmbeddingVector,
    model: string,
  ): Promise<void>;

  /** Return stored embedding metadata for startup backfill decisions. */
  getEmbeddingInfo?(nodeId: string): Promise<EmbeddingRecordInfo | null>;

  /** Query nodes by vector similarity. */
  querySimilarEmbeddings?(
    vector: EmbeddingVector,
    filter: SearchFilter,
    limit: number,
    threshold?: number,
  ): Promise<ScoredMemory[]>;

  /** Query edges, optionally filtered by source/target. */
  queryEdges(filter?: {
    sourceId?: string;
    targetId?: string;
    relation?: EdgeRelation;
  }): Promise<MemoryEdge[]>;

  /** Return the full graph (nodes + edges). */
  getGraph(): Promise<GraphSnapshot>;

  /**
   * Return every persisted embedding (node id + vector + model). Used
   * by memory consolidation. Implementations may return an empty
   * array when embeddings are not stored.
   */
  getAllEmbeddings?(): Promise<Array<{ nodeId: string; vector: EmbeddingVector; model: string }>>;

  /**
   * Update only the `namespace` of a node. Used by `archive` to
   * move a memory to the `archived` namespace.
   */
  setNodeNamespace?(id: string, namespace: string): Promise<void>;

  /** Set TTL on a node. */
  setTTL(id: string, seconds: number): Promise<void>;

  /** Clear TTL on a node. */
  clearTTL(id: string): Promise<void>;

  /** Delete expired nodes and return the count of deleted nodes. */
  sweepExpired(): Promise<number>;

  /** Get all nodes with a specific tag. */
  queryNodesByTag(tag: string): Promise<MemoryNode[]>;

  /** Delete all nodes and edges (batch operation). */
  deleteAllNodes(): Promise<void>;

  /** Close connections and release resources. */
  close(): Promise<void>;
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * Experimental feature flags.
 */
export interface ExperimentalConfig {
  /** Enable semantic search via embeddings (requires adapter). */
  semanticSearch?: boolean;
  /** Enable graph visualization export. */
  graphViz?: boolean;
  /** Enable namespace isolation. */
  namespaces?: boolean;
  /** Enable context injection from graph neighbours. */
  contextInjection?: boolean;
}

/**
 * Configuration options for a MemOS instance.
 */
export interface MemOSConfig {
  /**
   * Path to the SQLite database file.
   * @default "~/.memos/memos.db"
   */
  dbPath?: string;

  /**
   * Enable WAL mode for SQLite.
   * @default true
   */
  wal?: boolean;

  /**
   * Maximum number of memories to keep before LRU eviction.
   * Set to `0` to disable eviction.
   * @default 0
   */
  maxMemories?: number;

  /**
   * Auto-link threshold: minimum cosine-similarity score (bag-of-words)
   * between two nodes to automatically create an edge.
   * Set to `0` to disable auto-linking.
   * @default 0.3
   */
  autoLinkThreshold?: number;

  /**
   * Custom storage adapter. When provided, `dbPath` is ignored.
   */
  storage?: StorageAdapter;

  /**
   * Interval in seconds for the TTL expiration sweep.
   * Set to `0` to disable the sweep.
   * @default 60
   */
  sweepInterval?: number;

  /**
   * Experimental feature flags.
   */
  experimental?: ExperimentalConfig;

  /**
   * Embedding provider configuration for semantic and hybrid retrieval.
   */
  embeddings?: EmbeddingConfig;

  /**
   * Background embedding queue tuning. Only takes effect when an
   * embedding provider is configured. See `EmbeddingQueueConfig`.
   */
  embeddingQueue?: EmbeddingQueueConfig;
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/**
 * Export format options.
 */
export type ExportFormat = "json" | "markdown" | "obsidian";

/**
 * Options for exporting memories.
 */
export interface ExportOptions {
  /** Export format. */
  format?: ExportFormat;
  /** Output directory path (for markdown/obsidian). */
  output?: string;
  /** Only export memories with this tag. */
  tag?: string;
}

/**
 * Result of an export operation.
 */
export interface ExportResult {
  /** The format used. */
  format: ExportFormat;
  /** For JSON format, the serialized data. For file-based formats, the output directory. */
  data: string;
  /** Number of memories exported. */
  count: number;
}

// ---------------------------------------------------------------------------
// Import
// ---------------------------------------------------------------------------

/**
 * Options for importing memories.
 */
export interface ImportOptions {
  /** Source format: json file path, or directory of markdown/obsidian files. */
  source: string;
  /** Import format: json, markdown, or obsidian. Auto-detected from path if omitted. */
  format?: ImportFormat;
}

/**
 * Import format options.
 */
export type ImportFormat = "json" | "markdown" | "obsidian";

/**
 * Result of an import operation.
 */
export interface ImportResult {
  /** Number of memories imported. */
  count: number;
  /** Number of edges recreated (from wikilinks in obsidian format). */
  edgesCreated: number;
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/** Events emitted by the MemoryManager. */
export type MemOSEvent =
  | "node:created"
  | "node:updated"
  | "node:deleted"
  | "edge:created"
  | "edge:deleted"
  | "link:auto"
  | "eviction"
  | "ttl:expired"
  | "embedding:queued"
  | "embedding:started"
  | "embedding:complete"
  | "embedding:failed"
  | "embedding:retry"
  | "consolidation:complete"
  | "trust:changed"
  | "validity:changed"
  | "facts:extracted";

/** Event listener signature. */
export type MemOSEventListener = (data: unknown) => void;

// ---------------------------------------------------------------------------
// Memory consolidation
// ---------------------------------------------------------------------------

/** Options for {@link MemOS.dedupe}. */
export interface DedupeOptions {
  /** Cosine-similarity threshold above which two memories are merged. Default 0.92. */
  threshold?: number;
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** If true, do not delete or merge anything. Default false. */
  dryRun?: boolean;
  /** Cap on how many pairs to compare. Default 10_000. */
  maxPairs?: number;
}

/** A single merge performed by `dedupe()`. */
export interface DedupeMerge {
  /** The id of the surviving node. */
  kept: string;
  /** The ids of the nodes merged into the survivor and removed. */
  removed: string[];
  /** The reason this merge was selected. */
  reason: string;
  /** Mean cosine similarity across the cluster that was merged. */
  similarity: number;
}

/** Result returned by {@link MemOS.dedupe}. */
export interface DedupeResult {
  merges: DedupeMerge[];
  /** Number of distinct clusters that were detected. */
  clustersFound: number;
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.archive}. */
export interface ArchiveOptions {
  /** Move memories older than this many days. Default 90. */
  afterDays?: number;
  /** Cap on importance for archival. Default 0.3. */
  importanceBelow?: number;
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** If true, do not actually move anything. Default false. */
  dryRun?: boolean;
}

/** A single archive operation. */
export interface ArchiveMove {
  /** The id of the moved memory. */
  id: string;
  /** Reason it was archived (e.g. "stale_and_low_importance"). */
  reason: string;
}

/** Result returned by {@link MemOS.archive}. */
export interface ArchiveResult {
  moves: ArchiveMove[];
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.summarizeCluster}. */
export interface SummarizeClusterOptions {
  /** Namespace to cluster. Default "default". */
  namespace?: string;
  /** Minimum cluster size to summarize. Default 3. */
  minClusterSize?: number;
  /** Cosine-similarity threshold for cluster membership. Default 0.78. */
  threshold?: number;
  /** If true, do not actually create summary nodes. Default false. */
  dryRun?: boolean;
}

/** A cluster that was summarized. */
export interface ClusterSummary {
  /** The id of the newly-created summary node. Null when `dryRun: true`. */
  summaryId: string | null;
  /** The ids of the source nodes that the summary was derived from. */
  derivedFrom: string[];
  /** The generated summary text. */
  summary: string;
}

/** Result returned by {@link MemOS.summarizeCluster}. */
export interface SummarizeClusterResult {
  clusters: ClusterSummary[];
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.consolidate}. */
export interface ConsolidateOptions {
  /** Cosine threshold for dedupe. Default 0.92. */
  dedupeThreshold?: number;
  /** Move memories older than this many days. Default 90. */
  archiveAfterDays?: number;
  /** Cap on importance for archival. Default 0.3. */
  archiveImportanceBelow?: number;
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** If true, do not actually mutate anything. Default false. */
  dryRun?: boolean;
  /** Generate cluster summaries in addition to dedupe + archive. Default true. */
  summarize?: boolean;
  /** Minimum cluster size for summarization. Default 3. */
  minClusterSize?: number;
  /** Cosine threshold for cluster membership. Default 0.78. */
  clusterThreshold?: number;
}

/** Result returned by {@link MemOS.consolidate}. */
export interface ConsolidateResult {
  merges: DedupeMerge[];
  moves: ArchiveMove[];
  clusters: ClusterSummary[];
  dryRun: boolean;
  durationMs: number;
}

// ---------------------------------------------------------------------------
// Fact extraction
// ---------------------------------------------------------------------------

/**
 * A single message in a conversation, used by `extractFacts`.
 */
export interface ConversationMessage {
  /** Speaker role: "user", "assistant", or "system". */
  role: "user" | "assistant" | "system";
  /** Message text content. */
  content: string;
  /** Optional speaker name for multi-user conversations. */
  speaker?: string;
}

/**
 * A candidate fact extracted from a conversation.
 */
export interface ExtractedFact {
  /** The extracted fact text. */
  content: string;
  /** Inferred memory type. */
  type: MemoryType;
  /** Confidence in [0, 1]. */
  confidence: number;
  /** Optional tags inferred from context. */
  tags: string[];
  /** Source of the fact — usually `user_input` or `agent_inferred`. */
  source: MemorySource;
}

/**
 * Options for {@link MemOS.extractFacts}.
 */
export interface ExtractFactsOptions {
  /**
   * If true, automatically store all extracted facts with confidence >=
   * `minConfidence`. Default false — returns candidates without storing.
   */
  autoStore?: boolean;
  /** Only auto-store facts with confidence >= this threshold. Default 0.6. */
  minConfidence?: number;
  /** Namespace to store facts in (when autoStore is true). */
  namespace?: string;
  /**
   * When true, skip facts that are near-duplicates of existing memories.
   * Default true.
   */
  dedupe?: boolean;
  /** Cosine similarity threshold for dedup. Default 0.85. */
  dedupeThreshold?: number;
}

/** Result returned by {@link MemOS.extractFacts}. */
export interface ExtractFactsResult {
  /** Extracted fact candidates. */
  facts: ExtractedFact[];
  /** IDs of stored nodes (when `autoStore` is true). */
  storedIds: string[];
  /** Number of facts skipped as near-duplicates. */
  duplicates: number;
}

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

/**
 * Detailed diagnostics snapshot returned by `memos.diagnostics()`.
 */
export interface DiagnosticsResult {
  /** Total number of stored memories. */
  totalNodes: number;
  /** Total number of edges. */
  totalEdges: number;
  /** Number of memories with embeddings. */
  nodesWithEmbeddings: number;
  /** Number of memories with temporal validity set. */
  nodesWithValidity: number;
  /** Number of historical (superseded) memories. */
  historicalNodes: number;
  /** Number of memories with a TTL. */
  nodesWithTTL: number;
  /** Number of expired memories pending sweep. */
  expiredNodes: number;
  /** Average importance across all nodes. */
  avgImportance: number;
  /** Average trust score across all nodes. */
  avgTrustScore: number;
  /** Breakdown of nodes by provenance source. */
  bySource: Record<string, number>;
  /** Breakdown of nodes by memory type. */
  byType: Record<string, number>;
  /** Breakdown of nodes by namespace. */
  byNamespace: Record<string, number>;
  /** Database file size in bytes. */
  dbSizeBytes: number;
  /** Embedding queue status, if configured. */
  embeddingQueue?: EmbeddingQueueStatus;
  /** Whether the storage adapter supports optional methods. */
  storageCapabilities: {
    peekNode: boolean;
    evictLeastImportant: boolean;
    saveEmbedding: boolean;
    getAllEmbeddings: boolean;
    setNodeNamespace: boolean;
  };
}
