/**
 * MemOS — Universal memory layer for AI agents.
 *
 * Core type definitions. Every interface and type in the system
 * is defined here to provide a single source of truth for the
 * data model across modules.
 *
 * @module @memos/types
 */

// Type-only import: `ImportanceConfig` is defined in `src/importance.ts`,
// which itself imports `MemoryNode` from this file. Type-only circular
// imports are erased at compile time, so there is no runtime cycle.
import type { ImportanceConfig } from "./importance.js";

// ---------------------------------------------------------------------------
// Memory Nodes
// ---------------------------------------------------------------------------

/**
 * Semantic category for a memory node.
 *
 * - `fact`          — A discrete piece of information.
 * - `preference`    — A user or agent preference.
 * - `context`       — Conversational or situational context.
 * - `relationship`  — An observed relationship between entities.
 * - `entity`        — A named entity (person, place, thing).
 * - `custom`        — Application-defined type.
 */
export type MemoryType =
  "fact" | "preference" | "context" | "relationship" | "entity" | "custom";

/**
 * Provenance source for a memory node.
 *
 * - `user_input`     — Stated directly by the user. Highest trust.
 * - `agent_inferred` — Inferred by an agent from context.
 * - `external_data`  — Imported from an external source.
 * - `system`         — Generated by the system itself.
 */
export type MemorySource =
  "user_input" | "agent_inferred" | "external_data" | "system";

/**
 * Default trust score for each provenance source.
 */
export const DEFAULT_TRUST_SCORES: Record<MemorySource, number> = {
  user_input: 1.0,
  agent_inferred: 0.7,
  external_data: 0.5,
  system: 0.3,
};

/**
 * A single unit of memory stored in the graph.
 */
/**
 * Which retrieval pool a memory belongs to — the multi-granularity
 * structure from the LongMemEval-V2 design lessons:
 * - `event`      — raw statements as they were captured (the default; every
 *                  legacy memory reads as `event`).
 * - `note`       — distilled summaries produced by consolidation
 *                  (`summarizeCluster` writes here).
 * - `procedure`  — workflow/procedural knowledge ("how to" steps).
 * Pools are queryable via `SearchFilter.pool` and searched as separate
 * streams by multi-stream context packs.
 */
export type MemoryPool = "event" | "note" | "procedure";

/**
 * Typed multi-scope keys for isolating memories per user, agent, and run.
 * Composed into the underlying namespace string in fixed order
 * (`u:alice/a:coder/r:r1`) — see `src/scope.ts`. Hierarchical by default:
 * querying `{ user: "alice" }` surfaces every memory Alice's agents and
 * runs stored.
 */
export interface MemoryScope {
  /** Owner of the memories (e.g. end-user id). */
  user?: string;
  /** Which agent produced them. */
  agent?: string;
  /** Which session/run produced them. */
  run?: string;
}

export interface MemoryNode {
  /** Globally unique identifier (UUID v4). */
  id: string;
  /** Raw text content of the memory. */
  content: string;
  /** Extractive summary (auto-generated if not supplied). */
  summary: string;
  /** Semantic type of this memory. */
  type: MemoryType;
  /** Arbitrary metadata bag. Must be JSON-serialisable. */
  metadata: Record<string, unknown>;
  /**
   * Base importance score in [0, 1]. Set at write time (default 0.5) or
   * manually via `update`. Lifecycle decisions (eviction, archival)
   * derive an *effective* importance from this base plus recency decay
   * and access reinforcement — see `computeEffectiveImportance` in
   * `src/importance.ts`.
   */
  importance: number;
  /** Creation timestamp (Unix ms). */
  createdAt: number;
  /** Last-modified timestamp (Unix ms). */
  updatedAt: number;
  /** Number of times this node has been retrieved. */
  accessCount: number;
  /** Timestamp of last access (Unix ms). */
  lastAccessed: number;
  /** Custom tags for categorisation. */
  tags: string[];
  /** TTL expiration as Unix timestamp (seconds). null = no expiration. */
  expiresAt: number | null;
  /** Namespace for grouping memories (experimental). */
  namespace: string;
  /**
   * Temporal validity start (Unix ms). When set, the memory is
   * considered "active" from this point in time. null = always valid.
   */
  validFrom: number | null;
  /**
   * Temporal validity end (Unix ms). When set, the memory becomes
   * "historical" (excluded from default search) after this time.
   * null = no expiry. Superseded memories keep their validTo so the
   * history is queryable via `searchTemporal`.
   */
  validTo: number | null;
  /**
   * Where this memory originated. Used for provenance and trust
   * scoring.
   * - `user_input`     — Stated directly by the user. Highest trust.
   * - `agent_inferred` — Inferred by an agent from context. Lower trust.
   * - `external_data`  — Imported from an external source (API, file, etc.).
   * - `system`         — Generated by the system itself.
   */
  source: MemorySource;
  /**
   * Retrieval pool this memory belongs to (multi-granularity retrieval).
   * Optional for backward compatibility with custom storage adapters;
   * treated as `"event"` when absent.
   */
  pool?: MemoryPool;
  /**
   * Trust score in [0, 1]. Influences retrieval ranking. Starts at
   * 1.0 for `user_input`, 0.7 for `agent_inferred`, 0.5 for
   * `external_data`, 0.3 for `system`. Can be manually adjusted via
   * `memos.setTrust()`.
   */
  trustScore: number;
  /**
   * Dynamic confidence score in [0, 1]. Reflects how sure the system
   * is that this memory is still true, given new observations.
   * - Reinforced when new observations agree (confidence goes up)
   * - Revised when new observations partially conflict (confidence goes down)
   * - Superseded when new facts clearly replace old ones (marked historical)
   * Stored in metadata as `confidence` and `evidenceCount`.
   */
  confidence?: number;
  /** Number of evidence events (reinforces + revisions) that touched this memory. */
  evidenceCount?: number;
}

/**
 * Partial input accepted when creating a new memory.
 * Only `content` is required; everything else has defaults.
 */
export interface CreateMemoryInput {
  content: string;
  type?: MemoryType;
  metadata?: Record<string, unknown>;
  summary?: string;
  importance?: number;
  /** TTL in seconds from now. */
  ttl?: number;
  /** Custom tags. */
  tags?: string[];
  /** Namespace (experimental). */
  namespace?: string;
  /**
   * Typed multi-scope isolation. Composed into the namespace string
   * (fixed order user → agent → run); takes precedence over `namespace`
   * when both are supplied.
   */
  scope?: MemoryScope;
  /** Temporal validity start (Unix ms). null = always valid. */
  validFrom?: number | null;
  /** Temporal validity end (Unix ms). null = no expiry. */
  validTo?: number | null;
  /** Provenance source. Default: `user_input`. */
  source?: MemorySource;
  /**
   * Retrieval pool for this memory. Default: `"event"`. Use `"procedure"`
   * for workflow/how-to knowledge — multi-stream context packs search
   * procedures with a dedicated query stream.
   */
  pool?: MemoryPool;
  /**
   * One line of write-time context describing the situation this memory
   * was captured in (e.g. "stated while debugging the deploy pipeline").
   * Stored in `metadata.context`, prepended to the embedded text, and
   * included in context packs. When absent, the optional
   * `MemOSConfig.enrichMemory` hook is consulted.
   */
  context?: string;
  /** Trust score [0, 1]. Overrides the default for the chosen source. */
  trustScore?: number;
  /**
   * Dynamic confidence score [0, 1] for the confidence state machine.
   * Used to track how sure the system is that this memory is still true.
   * If omitted, defaults to INITIAL_CONFIDENCE (0.5).
   */
  confidence?: number;
  /**
   * Evidence count for the confidence state machine.
   * Number of reinforce/revise events this memory has accumulated.
   * If omitted, defaults to 0 for manually stored items.
   */
  evidenceCount?: number;
  /**
   * When true, apply the Hermes-style retain pre-filter (v1.6.26) before
   * writing: low-signal content (acknowledgements, chit-chat, near-empty
   * text) is skipped so long-term memory isn't flooded with noise that would
   * later bloat context-packs. Default: false (write always).
   */
  filterRetain?: boolean;
  /**
   * When true, run the evidence state machine before writing:
   * content that confirms an existing memory reinforces it (confidence ↑)
   * instead of writing a duplicate node, and content that contradicts it
   * supersedes the old version. Default: false — store() appends a new
   * node every time (use dedupe()/consolidate() for explicit merging).
   */
  evidenceLearning?: boolean;
}

/**
 * Partial update for an existing memory node.
 */
export interface UpdateMemoryInput {
  content?: string;
  summary?: string;
  type?: MemoryType;
  metadata?: Record<string, unknown>;
  importance?: number;
  tags?: string[];
  namespace?: string;
  /** Temporal validity start (Unix ms). */
  validFrom?: number | null;
  /** Temporal validity end (Unix ms). */
  validTo?: number | null;
  /** Provenance source. */
  source?: MemorySource;
  /** Trust score [0, 1]. */
  trustScore?: number;
  /** Dynamic confidence [0, 1] — updated by the evidence state machine. */
  confidence?: number;
  /** Evidence count — updated by the evidence state machine. */
  evidenceCount?: number;
}

// ---------------------------------------------------------------------------
// Memory Edges
// ---------------------------------------------------------------------------

/**
 * Semantic relation between two memory nodes.
 *
 * - `relates_to`     — General association.
 * - `contradicts`    — The target contradicts the source.
 * - `supports`       — The target supports the source.
 * - `derived_from`   — The source was derived from the target.
 * - `part_of`        — The source is a part of the target.
 * - `custom`         — Application-defined relation.
 */
export type EdgeRelation =
  | "relates_to"
  | "contradicts"
  | "supports"
  | "derived_from"
  | "part_of"
  | "temporal_precedes"
  | "custom";

/**
 * A directed, weighted edge connecting two memory nodes.
 */
export interface MemoryEdge {
  /** Globally unique identifier (UUID v4). */
  id: string;
  /** Source node ID. */
  sourceId: string;
  /** Target node ID. */
  targetId: string;
  /** Semantic relation label. */
  relation: EdgeRelation;
  /** Edge weight in [0, 1]. */
  weight: number;
  /** Arbitrary metadata bag. */
  metadata: Record<string, unknown>;
  /**
   * Transaction/ingest time (Unix ms): when MemOS learned the fact.
   * This is the bitemporal transaction-time axis — it is never renamed
   * or repurposed; event-time validity lives in `validFrom`/`validTo`.
   */
  createdAt: number;
  /**
   * Event-time validity start (Unix ms): when the fact became true in the
   * world. `null`/undefined = open-ended (still true, or unknown).
   */
  validFrom?: number | null;
  /**
   * Event-time validity end (Unix ms): when the fact ceased to be true.
   * `null`/undefined = open-ended (still true). Supersession stamps this
   * instead of deleting the row, preserving add-only history for as-of
   * (time-travel) reads.
   */
  validTo?: number | null;
}

/**
 * Input for creating a new edge.
 */
export interface CreateEdgeInput {
  sourceId: string;
  targetId: string;
  relation?: EdgeRelation;
  weight?: number;
  metadata?: Record<string, unknown>;
  /**
   * Event-time validity start (Unix ms): when the fact became true in the
   * world. `null`/undefined = open-ended.
   */
  validFrom?: number | null;
  /**
   * Event-time validity end (Unix ms): when the fact ceased to be true.
   * `null`/undefined = open-ended.
   */
  validTo?: number | null;
}

// ---------------------------------------------------------------------------
// Search & Query
// ---------------------------------------------------------------------------

/**
 * Filter criteria for searching memories.
 */
export interface SearchFilter {
  /** Full-text search query. */
  query?: string;
  /** Filter by memory type. */
  type?: MemoryType;
  /** Minimum importance threshold [0, 1]. */
  minImportance?: number;
  /** Maximum importance threshold [0, 1]. */
  maxImportance?: number;
  /** Metadata key-value filter. */
  metadata?: Record<string, unknown>;
  /** Limit the number of results. */
  limit?: number;
  /** Offset for pagination. */
  offset?: number;
  /** Sort field. */
  sortBy?:
    | "importance"
    | "createdAt"
    | "updatedAt"
    | "accessCount"
    | "relevance"
    | "trustScore";
  /** Sort direction. */
  sortOrder?: "asc" | "desc";
  /** Filter by tags (AND logic — node must have ALL specified tags). */
  tags?: string[];
  /** Filter by namespace. */
  namespace?: string;
  /**
   * Typed multi-scope filter. Composed into a namespace prefix; with the
   * default `"hierarchical"` match, `{ user: "alice" }` surfaces every
   * memory stored under Alice's agents and runs. Set
   * `scopeMatch: "exact"` to require the identical namespace string.
   */
  scope?: MemoryScope;
  /** How `scope` matches stored namespaces. Default `"hierarchical"`. */
  scopeMatch?: "exact" | "hierarchical";
  /** Internal: pre-composed LIKE prefix for namespace matching. */
  namespacePrefix?: string;
  /**
   * Filter by retrieval pool. Pass a single pool or a list (OR logic).
   * Memories written before pools existed read as `"event"`.
   */
  pool?: MemoryPool | MemoryPool[];
  /** Filter by provenance source. */
  source?: MemorySource;
  /** Minimum trust score [0, 1]. */
  minTrustScore?: number;
  /**
   * When true (default), exclude memories whose `validTo` is in the
   * past (i.e. historical/superseded memories). Set to false to
   * include historical memories.
   */
  includeHistorical?: boolean;
  /**
   * FTS term-join operator for the keyword leg.
   *
   * - `"AUTO"` (default): run the precision `AND` query first; when it
   *   matches nothing, relax to an `OR` query so partial-term matches
   *   still surface. Precise, and the historical default.
   * - `"AND"`: every query term must appear (forced precision).
   * - `"OR"`: any term may appear (forced recall — useful for
   *   multi-evidence retrieval where relevant facts rarely share every
   *   query term; noisier for single-fact queries).
   */
  ftsOperator?: "AUTO" | "AND" | "OR";
  /**
   * When true, expand the top base results with their "session siblings" —
   * other memories sharing the same `sessionId` (or `instanceId`) metadata
   * value. Multi-hop / multi-evidence answers typically live across many turns
   * of one conversation, so once a single relevant turn is retrieved, pulling
   * its conversation neighbours into the ranking materially raises All-Evidence
   * Recall. Deterministic, model-free, and OFF by default so single-node
   * retrieval keeps its exact ordering.
   */
  sessionExpansion?: boolean;
  /** Timestamp filter (Unix ms): only return memories valid at this time. */
  validAt?: number;
  /**
   * How many candidates each hybrid-search leg fetches before fusion.
   * Overrides the default `max(limit * 4, 20)`. Higher values widen the
   * recall pool (useful when a reranker or expansion stage narrows
   * afterwards) at linear scan cost.
   */
  candidateDepth?: number;
  /**
   * Drop results whose stored embedding is a near-duplicate (cosine >=
   * `experimental.searchDedupThreshold`, default 0.95) of an
   * already-selected result. Near-duplicates waste top-K slots that
   * distinct evidence needs — multi-evidence questions score one node per
   * duplicate otherwise. Off by default.
   */
  semanticDedup?: boolean;
}

/**
 * Options for `MemOS.semanticSearch()`. Accepts every `SearchFilter` field
 * (namespace, tags, type, limit, …) plus the semantic similarity cutoff.
 */
export interface SemanticSearchOptions extends SearchFilter {
  /** Minimum similarity score in [0, 1]. Default 0.1. */
  threshold?: number;
}

/**
 * AI Trio context pack — a token-budgeted, ranked, namespace-filtered
 * slice of memory intended to be folded into an LLM prompt by Guardian.
 *
 * See `docs/ai-trio-contracts.md` for the full contract.
 */
export interface ContextPackItem {
  id: string;
  content: string;
  summary: string;
  score: number;
  scores?: {
    keyword?: number;
    semantic?: number;
    hybrid?: number;
  };
  trust: string;
  source: string;
  tags: string[];
  updatedAt: string;
}

export interface ContextPack {
  schema: "ai-trio.memos.context-pack.v1";
  query: string;
  namespace: string;
  tokenBudget: number;
  items: ContextPackItem[];
}

/**
 * A memory node bundled with its relevance score after a search.
 */
export interface ScoredMemory {
  node: MemoryNode;
  /** Relevance score returned by the search algorithm. */
  score: number;
  /** Optional score breakdown for hybrid retrieval. `graph` marks a
   * node injected by the graph-expansion leg, `session` one pulled in
   * by session-sibling expansion, `rerank` the cross-encoder score
   * (squashed to [0,1]) from the two-stage reranking pass, `entity` the
   * query-entity overlap (in [0,1]) that earned the entity-fusion boost. */
  scores?: {
    keyword?: number;
    semantic?: number;
    hybrid?: number;
    graph?: number;
    session?: number;
    rerank?: number;
    entity?: number;
    /**
     * Present when read-time contradiction resolution demoted this
     * result: the demotion factor applied (see
     * CONTRADICTION_DEMOTION_FACTOR in src/contradictions.ts).
     */
    contradiction_demoted?: number;
  };
}

/**
 * Lifecycle status of a recorded contradiction pair.
 *
 * - `unresolved`: detected at write time by the rule-based detector;
 *   both versions are kept (add-only). Read-time resolution demotes the
 *   older member. Sleep-time LLM adjudication (future) may resolve it.
 * - `resolved`: a contradiction outcome was confirmed through the
 *   evidence state machine (e.g. an old memory superseded by a new
 *   version) — the pair is recorded for provenance.
 */
export type ContradictionStatus = "unresolved" | "resolved";

/**
 * A recorded contradiction pair: two memory nodes about the same
 * subject that disagree. Node ids are stored in canonical (sorted)
 * order so the UNIQUE(node_a, node_b) constraint dedups pairs
 * regardless of insertion order.
 */
export interface ContradictionRecord {
  id: string;
  nodeA: string;
  nodeB: string;
  detectedAt: number;
  status: ContradictionStatus;
}

// ---------------------------------------------------------------------------
// Embeddings
// ---------------------------------------------------------------------------

export type EmbeddingVector = number[];

/**
 * Runtime resolution metadata for an embedding provider instance.
 *
 * Benchmarks (and any caller who cares about reproducibility) use this to
 * verify that the provider they REQUESTED is the provider that actually
 * loaded — in particular to detect the FastEmbed local-hash fallback that
 * activates when the transformers package is missing.
 */
export interface EmbeddingRuntimeInfo {
  /** Provider kind the caller asked for, e.g. "fastembed". */
  requestedProvider: string;
  /** Provider actually serving embeddings, e.g. "fastembed" or
   * "local-hash-fallback". Equal to `requestedProvider` when no fallback. */
  resolvedProvider: string;
  /** Model the caller asked for. */
  requestedModel: string;
  /** Model actually producing vectors. */
  resolvedModel: string;
  /** Model revision/commit when the provider exposes one, else null. */
  modelRevision: string | null;
  /** Dimensions the caller declared. */
  requestedDimensions: number;
  /** Dimensions observed on the most recent embed call, or null before
   * the first call. Differs from `requestedDimensions` only when the
   * provider's real output shape disagrees with configuration. */
  observedDimensions: number | null;
  /** True when the requested backend did NOT load and a fallback is
   * serving embeddings instead. Only meaningful after the first embed
   * call (or an explicit probe) has run. */
  fallbackActive: boolean;
  /** Human-readable reason for the fallback, or null when none occurred. */
  fallbackReason: string | null;
}

export interface EmbeddingProvider {
  /** Stable provider identifier, e.g. "local-hash" or "ollama". */
  id: string;
  /** Human-readable embedding model name. */
  model: string;
  /** Expected vector dimensionality. */
  dimensions: number;
  /**
   * Runtime resolution metadata (requested vs. resolved provider/model,
   * fallback status). Optional so custom providers need not implement it;
   * when absent, callers should assume the provider IS what it claims and
   * there is no fallback. The built-in FastEmbed provider implements it to
   * expose the local-hash fallback state.
   */
  getRuntimeInfo?(): EmbeddingRuntimeInfo;
  /** Generate a normalized embedding vector for a text input. */
  embed(text: string): Promise<EmbeddingVector>;
  /**
   * Optional batch embedding. If the provider can batch, override this to
   * amortize network round-trips. Default implementation calls `embed` for
   * each text in order. The returned vectors must be in the same order as
   * the input `texts` array.
   */
  batchEmbed?(texts: string[]): Promise<EmbeddingVector[]>;
  /**
   * Embed a QUERY — a short natural-language retrieval question.
   *
   * Many modern retrieval models (e.g. the Liquid E / e5 families, and
   * Cohere embed-v3) are trained for an asymmetric query/document setting:
   * they expect an instruction or "query" prefix on the query side and plain
   * text on the document side. Routing queries through a dedicated method lets
   * providers apply that signal, which materially improves semantic recall for
   * paraphrase questions.
   *
   * Optional for backward compatibility: when a provider does not implement it,
   * `embedQuery`/`embedDocuments` default to the plain `embed` path so
   * existing custom providers keep working unchanged.
   */
  embedQuery?(text: string): Promise<EmbeddingVector>;
  /**
   * Embed a batch of DOCUMENTS (the persisted memory contents) for indexing.
   *
   * Optional; defaults to `batchEmbed`, falling back to per-text `embed`.
   * Providers that distinguish query from document mode should use the document
   * input type here (e.g. Cohere `search_document`).
   */
  embedDocuments?(texts: string[]): Promise<EmbeddingVector[]>;
}

export type EmbeddingProviderKind =
  | "local-hash"
  | "ollama"
  | "openai-compatible"
  | "voyage"
  | "cohere"
  | "fastembed";

export interface EmbeddingConfig {
  /** Enables embedding generation. Defaults to true when semantic search is enabled. */
  enabled?: boolean;
  /** Built-in provider kind, or a custom provider implementation. */
  provider?: EmbeddingProviderKind | EmbeddingProvider;
  /** Provider model name. */
  model?: string;
  /** Embedding vector dimensions. */
  dimensions?: number;
  /** Base URL for Ollama or OpenAI-compatible embedding endpoints. */
  baseUrl?: string;
  /** API key for OpenAI-compatible embedding endpoints. */
  apiKey?: string;
  /**
   * Prefix prepended to QUERY text before embedding. Asymmetric retrieval
   * models are trained with a query-side instruction and silently degrade
   * without it — e.g. Liquid LFM2.5-Embedding and e5 models expect
   * `"query: "`. Empty (default) sends queries as-is.
   */
  queryPrefix?: string;
  /**
   * Prefix prepended to DOCUMENT text (stored memory content) before
   * embedding at index time. e.g. Liquid LFM2.5-Embedding and e5 models
   * expect `"document: "`. Empty (default) sends documents as-is.
   */
  documentPrefix?: string;
  /**
   * Which node text to embed at store time: the raw `content`, or
   * `summary + "\n" + content` (the historical default — for short facts
   * the extractive summary roughly doubles the embedded tokens).
   */
  embedText?: "content" | "summary+content";
}

export interface EmbeddingRecordInfo {
  model: string;
  dimensions: number;
  updatedAt: number;
}

/**
 * Per-node embedding pipeline status. `pending` means the node has been
 * stored but its embedding has not been computed yet. `ready` means the
 * persisted vector is fresh for the current provider/model. `failed`
 * means the most recent attempt gave up after retries.
 */
export type EmbeddingNodeStatus =
  "pending" | "queued" | "running" | "ready" | "failed";

/** Lightweight status snapshot returned by `memos.embeddingStatus()`. */
export interface EmbeddingNodeStatusInfo {
  nodeId: string;
  status: EmbeddingNodeStatus;
  attempts: number;
  lastError: string | null;
  updatedAt: number;
}

/** Aggregate status returned by `memos.embeddingStatus()` (no args). */
export interface EmbeddingQueueStatus {
  pending: number;
  running: number;
  total: number;
  nodes: EmbeddingNodeStatusInfo[];
}

/**
 * Configuration for the background embedding queue. All fields are
 * optional; sensible defaults are used when omitted.
 */
export interface EmbeddingQueueConfig {
  /** Max concurrent in-flight embed calls. Default 2. */
  concurrency?: number;
  /**
   * Max pending jobs drained into a single `batchEmbed()` call when the
   * provider supports batching (array-input HTTP endpoints). Default 1 =
   * one `embed()` call per job. Groups that fail fall back to per-job
   * retries.
   */
  batchSize?: number;
  /** Max buffered jobs before `enqueue` throws. Default 10000. */
  maxQueueSize?: number;
  /** Max retry attempts per job before marking it failed. Default 3. */
  maxRetries?: number;
  /** Base backoff in ms; retries use exponential backoff. Default 250. */
  retryBackoffMs?: number;
  /**
   * Coalescing delay in ms before a fully-idle queue picks up
   * newly-enqueued work. Default 5. Lets rapid sequential `store()` calls
   * form full `batchSize` groups instead of one single-job group each.
   * Set to 0 for immediate microtask pickup.
   */
  batchLingerMs?: number;
  /**
   * If true, `store()` waits for the embedding to complete before
   * returning. Default false — background mode. Tests and the CLI
   * `memos flush-embeddings` command benefit from this being false.
   */
  synchronous?: boolean;
}

// ---------------------------------------------------------------------------
// Graph
// ---------------------------------------------------------------------------

/**
 * Full in-memory graph snapshot.
 */
export interface GraphSnapshot {
  nodes: MemoryNode[];
  edges: MemoryEdge[];
}

// ---------------------------------------------------------------------------
// Storage Adapter Interface
// ---------------------------------------------------------------------------

/**
 * Backend-agnostic storage contract.
 *
 * Any persistence backend (SQLite, Postgres, Redis, Qdrant …) must
 * implement this interface. The core engine only depends on this
 * contract, never on a concrete backend.
 */
export interface StorageAdapter {
  /** Initialise tables / indices / connections. Called once at startup. */
  init(): Promise<void>;

  /** Persist a new memory node. Returns the created node. */
  saveNode(node: MemoryNode): Promise<MemoryNode>;

  /** Retrieve a node by ID. Returns `null` when not found.
   *  Implementations should bump the access stats (access_count,
   *  last_accessed) on read. For side-effect-free reads, use `peekNode`. */
  getNode(id: string): Promise<MemoryNode | null>;

  /**
   * Side-effect-free variant of `getNode`. Does not increment
   * `access_count` or update `last_accessed`. Use for internal lookups
   * where the read is not a user-initiated retrieval — e.g. tag
   * updates, TTL changes, eviction candidate selection.
   */
  peekNode?(id: string): Promise<MemoryNode | null>;

  /**
   * Delete the single least-important node, where "least important" is
   * defined as lowest `importance` then oldest `last_accessed`.
   * Returns the id of the deleted node, or null if the table is empty.
   * Implementations may fall back to in-memory selection if SQL is
   * not appropriate.
   */
  evictLeastImportant?(): Promise<string | null>;

  /** Partially update a node. Returns the updated node. */
  updateNode(id: string, input: UpdateMemoryInput): Promise<MemoryNode | null>;

  /** Delete a node and all connected edges. */
  deleteNode(id: string): Promise<boolean>;

  /** Persist a new edge. Returns the created edge. */
  saveEdge(edge: MemoryEdge): Promise<MemoryEdge>;

  /**
   * Batch-insert multiple edges in a single transaction.
   * Falls back to individual saveEdge calls when not implemented.
   */
  saveEdgesBatch?(edges: MemoryEdge[]): Promise<MemoryEdge[]>;

  /** Retrieve an edge by ID. */
  getEdge(id: string): Promise<MemoryEdge | null>;

  /** Delete an edge by ID. */
  deleteEdge(id: string): Promise<boolean>;

  /**
   * Close (invalidate) the currently-valid edges incident to a node by
   * stamping `valid_to = validTo`. Rows are updated, never deleted, so
   * as-of reads at earlier timestamps still return them.
   * Returns the number of edges closed.
   */
  closeEdgesForNode?(nodeId: string, validTo: number): Promise<number>;

  /** Query nodes with filters. */
  queryNodes(filter: SearchFilter): Promise<ScoredMemory[]>;

  /** Persist an embedding vector for a node. */
  saveEmbedding?(
    nodeId: string,
    vector: EmbeddingVector,
    model: string,
  ): Promise<void>;

  /** Return stored embedding metadata for startup backfill decisions. */
  getEmbeddingInfo?(nodeId: string): Promise<EmbeddingRecordInfo | null>;

  /**
   * Return stored embedding metadata for every node in one round trip.
   * Optional bulk counterpart to `getEmbeddingInfo` — lets startup
   * backfill avoid one SELECT per node. Storages that don't implement it
   * fall back to per-node `getEmbeddingInfo` calls.
   */
  getAllEmbeddingInfos?(): Promise<
    Array<{ nodeId: string } & EmbeddingRecordInfo>
  >;

  /** Query nodes by vector similarity. */
  querySimilarEmbeddings?(
    vector: EmbeddingVector,
    filter: SearchFilter,
    limit: number,
    threshold?: number,
    /**
     * When provided, only rows stored by this exact model are compared.
     * Cosine similarity is meaningless across models, and two different
     * models can share a dimensionality — dimension equality alone does
     * not prevent silently mixing incompatible vectors.
     */
    model?: string,
  ): Promise<ScoredMemory[]>;

  /** Counts of stored embeddings grouped by model (reindex/audit support). */
  getEmbeddingModelCounts?(): Promise<Array<{ model: string; count: number }>>;

  /**
   * Bulk-fetch stored embedding vectors for the given node ids.
   * Used by write-time contradiction detection to avoid one SELECT per
   * neighbor. Returns only ids that have a stored vector.
   */
  getEmbeddingVectors?(
    nodeIds: string[],
  ): Promise<Map<string, EmbeddingVector>>;

  /** Delete all embedding rows stored by the given model. Returns the count. */
  deleteEmbeddingsByModel?(model: string): Promise<number>;

  /** Query edges, optionally filtered by source/target. */
  queryEdges(filter?: {
    sourceId?: string;
    targetId?: string;
    relation?: EdgeRelation;
    /**
     * Bitemporal as-of read: when provided, only edges whose event-time
     * validity interval covers this Unix-ms timestamp are returned
     * (NULL bounds are open-ended). Default returns all edges.
     */
    validAt?: number;
  }): Promise<MemoryEdge[]>;

  /**
   * Record a contradiction pair between two memory nodes. Node ids are
   * canonicalized (sorted) by the implementation so the UNIQUE constraint
   * dedups reversed pairs. Insert is idempotent (no-op when the pair is
   * already recorded).
   */
  addContradiction?(
    nodeA: string,
    nodeB: string,
    status?: ContradictionStatus,
  ): Promise<ContradictionRecord>;

  /**
   * Return recorded contradiction pairs where node_a OR node_b is in
   * `nodeIds` — the bounded read-time lookup for
   * `resolveContradictionsAtRead`.
   */
  getContradictionPairsFor?(nodeIds: string[]): Promise<ContradictionRecord[]>;

  /** Transition a contradiction record between `unresolved`/`resolved`. */
  updateContradictionStatus?(
    id: string,
    status: ContradictionStatus,
  ): Promise<void>;

  /** Return the full graph (nodes + edges). */
  getGraph(): Promise<GraphSnapshot>;

  /**
   * Return every persisted embedding (node id + vector + model). Used
   * by memory consolidation. Implementations may return an empty
   * array when embeddings are not stored.
   */
  getAllEmbeddings?(): Promise<
    Array<{ nodeId: string; vector: EmbeddingVector; model: string }>
  >;

  /**
   * Update only the `namespace` of a node. Used by `archive` to
   * move a memory to the `archived` namespace.
   */
  setNodeNamespace?(id: string, namespace: string): Promise<void>;

  /** Set TTL on a node. */
  setTTL(id: string, seconds: number): Promise<void>;

  /** Clear TTL on a node. */
  clearTTL(id: string): Promise<void>;

  /** Delete expired nodes and return the count of deleted nodes. */
  sweepExpired(): Promise<number>;

  /** Get all nodes with a specific tag. */
  queryNodesByTag(tag: string): Promise<MemoryNode[]>;

  /** Delete all nodes and edges (batch operation). */
  deleteAllNodes(): Promise<void>;

  /** Close connections and release resources. */
  close(): Promise<void>;
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * Experimental feature flags.
 */
export interface ExperimentalConfig {
  /**
   * @deprecated No longer required — `semanticSearch()` works without it.
   * Kept as a shorthand for enabling embeddings with the default provider
   * (equivalent to `embeddings: { enabled: true }`).
   */
  semanticSearch?: boolean;
  /** Enable graph visualization export. */
  graphViz?: boolean;
  /** Enable namespace isolation. */
  namespaces?: boolean;
  /** Enable context injection from graph neighbours. */
  contextInjection?: boolean;
  /**
   * Run the evidence state machine on every `store()`: similar existing
   * memories are reinforced, revised, or superseded, and near-duplicates
   * (similarity >= 0.92) are folded into the existing node instead of
   * being written again. Default: true.
   */
  evidenceOnStore?: boolean;
  /**
   * After a node's embedding is persisted, auto-link it to its top
   * embedding-similarity neighbours (cosine >= 0.6, max 8 edges) in
   * addition to the bag-of-words links. Only active when an embedding
   * provider is configured. Default: true.
   */
  embeddingAutoLink?: boolean;
  /**
   * Apply a gentle recency boost to hybrid search ranking. Off by
   * default: enabling it makes scores time-dependent, which relaxes the
   * score-reproducibility guarantee in `docs/ai-trio-contracts.md`.
   * Default: false.
   */
  recencyBoost?: boolean;
  /**
   * Graph-expansion recall leg for hybrid search. After fusion, the top
   * `maxSeeds` results are expanded along their graph edges and unseen
   * neighbours are injected into the ranking at `seedScore * scoreFactor`
   * (capped at `maxAdded` extra nodes). Useful for multi-evidence /
   * multi-hop queries where related facts are connected by
   * `relates_to`/`supports` edges but neither retrieval leg surfaces them.
   * Off by default.
   */
  graphExpansion?: {
    enabled?: boolean;
    /** How many top fused results to expand along edges. Default 3. */
    maxSeeds?: number;
    /** Maximum neighbours injected per query. Default 5. */
    maxAdded?: number;
    /** Injected neighbour score = seed score × this factor. Default 0.85. */
    scoreFactor?: number;
  };
  /**
   * Two-stage reranking: after fusion, the top `candidates` results are
   * re-scored by a cross-encoder served over an HTTP `/rerank` endpoint
   * (e.g. llama-server with bge-reranker-v2-m3) and the final ranking is
   * reordered by relevance score. The first stage (hybrid search) exists
   * to recall; the reranker decides what the caller actually sees. On
   * endpoint failure the fused order is kept unchanged (graceful
   * degradation). Off by default.
   */
  /**
   * Cosine threshold for the opt-in `filter.semanticDedup` in hybrid
   * search. Default 0.95 — near-verbatim duplicates only.
   */
  searchDedupThreshold?: number;
  rerank?: {
    /** Base URL of the rerank server, e.g. "http://127.0.0.1:8081".
     *  Receives `POST {endpoint}/rerank` with
     *  `{ model, query, documents: string[] }`. */
    endpoint: string;
    /** Bearer token for the rerank endpoint, when required. */
    apiKey?: string;
    /** Model name sent to the endpoint (many local servers ignore it). */
    model?: string;
    /** How many fused candidates to submit for reranking. Default 50. */
    candidates?: number;
    /**
     * Truncate each reranked document to this many characters before
     * sending. Cross-encoder relevance signal lives in the first few
     * hundred tokens, and capping pair length keeps the request's token
     * count predictable — long-tail documents otherwise force many extra
     * GPU waves on the rerank server. Default 0 = send full documents.
     */
    maxDocChars?: number;
    /** Request timeout in ms. Default 5000. */
    timeoutMs?: number;
  };
}

/**
 * Tunable knobs for the hybrid-search Reciprocal Rank Fusion. Lives in
 * `types.ts` (dependency-free) and is re-exported by `src/retrieval.ts`,
 * where `fuseResults()` consumes it. `MemOSConfig.fusion` forwards these
 * to every hybrid search; unset fields fall back to `retrieval.ts`
 * defaults.
 */
export interface FusionOptions {
  /** RRF constant K. Larger K flattens rank differences. Default 60. */
  rrfK?: number;
  /** Weight of the keyword (FTS5) leg. Default 0.8. */
  keywordWeight?: number;
  /** Weight of the semantic (embedding) leg. Default 0.2. */
  semanticWeight?: number;
  /**
   * Lower bound of the trust multiplier (applied as
   * `trustFloor + trustScore * (1 - trustFloor)`). Default 0.7.
   * Set to 1.0 to disable trust weighting.
   */
  trustFloor?: number;
  /**
   * Strength of the confidence/trust combined multiplier from the
   * evidence state machine. Default 0.35. Set to 0 to disable
   * confidence-aware ranking.
   */
  confidenceWeightStrength?: number;
  /**
   * Recency half-life in ms for the tie-break among near-equal scores.
   * Default 30 days. Set to 0 to disable recency tie-breaking.
   */
  recencyHalfLifeMs?: number;
  /**
   * Reference "now" for recency computations. Defaults to wall-clock;
   * injectable for deterministic tests/benchmarks.
   */
  nowMs?: number;
  /**
   * Entities extracted from the query (populated automatically by
   * `hybridSearch` via `extractQueryEntities`). When non-empty, memories
   * whose tags / `metadata.entities` overlap the query entities receive a
   * post-fusion boost — the third retrieval signal alongside keyword and
   * semantic (see the 2026 fused multi-signal retrieval consensus).
   */
  queryEntities?: string[];
  /**
   * Strength of the entity-overlap boost: `score *= 1 + entityWeight *
   * overlap`. Default 0.15. Set to 0 to disable entity-fused scoring.
   */
  entityWeight?: number;
}

/**
 * Configuration options for a MemOS instance.
 */
export interface MemOSConfig {
  /**
   * Optional write-time contextual enrichment hook (contextual retrieval,
   * Anthropic-style). Called once per `store()` with the memory's signals;
   * return a single line describing the situation the memory was captured
   * in (e.g. "stated while debugging the deploy pipeline"). The line is
   * stored in `metadata.context`, prepended to the embedded text, and
   * surfaced in context packs — it makes embeddings carry situational
   * meaning, which is the best-attested cheap retrieval upgrade in the
   * literature. Wire this to a local LLM (0.6B-class is enough) or any
   * heuristic. Errors are swallowed (fail-soft) and `opts.context`
   * always takes precedence over the hook.
   */
  enrichMemory?: (input: {
    content: string;
    type: MemoryType;
    tags: string[];
    source: MemorySource;
    namespace: string;
  }) => Promise<string | null | undefined> | string | null | undefined;
  /**
   * Deployment-specific entity aliases for fused retrieval scoring,
   * merged over the built-in table (`BUILTIN_ENTITY_ALIASES` in
   * `src/entity-extraction.ts`). Keys and values are matched
   * case-insensitively. Use this to canonicalize domain vocabulary —
   * e.g. `{ "sso": "auth", "okta": "auth" }` — so memories surface no
   * matter which phrasing a query uses.
   */
  entityAliases?: Record<string, string>;
  /**
   * Optional LLM distillation hook for `summarizeCluster` /
   * `consolidate`. Receives the contents of one cluster and returns an
   * abstractive summary (a runbook-style note — the highest-value
   * granularity in the LongMemEval-V2 ablations). When omitted or when
   * the hook fails/returns empty, the extractive summarizer is used.
   * Wire this to a local 0.6B–4B model for fully-offline consolidation.
   */
  summarizeClusterLlm?: (input: {
    contents: string[];
    sourceIds: string[];
  }) => Promise<string | null | undefined> | string | null | undefined;
  /**
   * Hybrid-search fusion tuning forwarded to `fuseResults()` on every
   * hybrid search. Unset fields use `src/retrieval.ts` defaults
   * (keyword 0.8 / semantic 0.2 / K 60 — tuned for the hash baseline;
   * stronger embedding models generally want a higher semantic weight).
   */
  fusion?: FusionOptions;

  /**
   * Path to the SQLite database file.
   * @default "~/.memos/memos.db"
   */
  dbPath?: string;

  /**
   * Enable WAL mode for SQLite.
   * @default true
   */
  wal?: boolean;

  /**
   * Maximum number of memories to keep before LRU eviction.
   * Set to `0` to disable eviction.
   * @default 0
   */
  maxMemories?: number;

  /**
   * Auto-link threshold: minimum cosine-similarity score (bag-of-words)
   * between two nodes to automatically create an edge.
   * Set to `0` to disable auto-linking.
   * @default 0.3
   */
  autoLinkThreshold?: number;

  /**
   * Custom storage adapter. When provided, `dbPath` is ignored.
   */
  storage?: StorageAdapter;

  /**
   * Options forwarded to the built-in SQLite storage adapter when
   * `storage` is not supplied. `vectorCacheEntries` bounds the in-process
   * parsed-vector cache (default 25,000 ≈ 100MB at 1024 dims); lower it
   * for memory-constrained hosts.
   */
  storageOptions?: { vectorCacheEntries?: number };
  /**
   * Encryption key for at-rest encryption of the SQLite database.
   * Requires the optional `better-sqlite3-multiple-ciphers` driver
   * (`npm i better-sqlite3-multiple-ciphers`). Falls back to the
   * `MEMOS_KEY` environment variable. Only NEW databases get encrypted —
   * convert an existing plaintext DB with `memos encrypt`.
   */
  cipherKey?: string;

  /**
   * Interval in seconds for the TTL expiration sweep.
   * Set to `0` to disable the sweep.
   * @default 60
   */
  sweepInterval?: number;

  /**
   * Experimental feature flags.
   */
  experimental?: ExperimentalConfig;

  /**
   * Effective importance model tuning. Controls how recency decay and
   * access reinforcement modulate the base `importance` for eviction
   * and archival decisions. See `ImportanceConfig` in `src/importance.ts`.
   */
  importance?: ImportanceConfig;

  /**
   * Half-life (days) for the optional recency boost in hybrid search
   * ranking. Only used when `experimental.recencyBoost` is enabled.
   * @default 14
   */
  recencyHalfLifeDays?: number;

  /**
   * Embedding provider configuration for semantic and hybrid retrieval.
   */
  embeddings?: EmbeddingConfig;

  /**
   * Background embedding queue tuning. Only takes effect when an
   * embedding provider is configured. See `EmbeddingQueueConfig`.
   */
  embeddingQueue?: EmbeddingQueueConfig;
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/**
 * Export format options.
 */
export type ExportFormat = "json" | "markdown" | "obsidian";

/**
 * Options for exporting memories.
 */
export interface ExportOptions {
  /** Export format. */
  format?: ExportFormat;
  /** Output directory path (for markdown/obsidian). */
  output?: string;
  /** Only export memories with this tag. */
  tag?: string;
}

/**
 * Result of an export operation.
 */
export interface ExportResult {
  /** The format used. */
  format: ExportFormat;
  /** For JSON format, the serialized data. For file-based formats, the output directory. */
  data: string;
  /** Number of memories exported. */
  count: number;
}

// ---------------------------------------------------------------------------
// Import
// ---------------------------------------------------------------------------

/**
 * Options for importing memories.
 */
export interface ImportOptions {
  /** Source format: json file path, or directory of markdown/obsidian files. */
  source: string;
  /** Import format: json, markdown, or obsidian. Auto-detected from path if omitted. */
  format?: ImportFormat;
}

/**
 * Import format options.
 */
export type ImportFormat = "json" | "markdown" | "obsidian";

/**
 * Result of an import operation.
 */
export interface ImportResult {
  /** Number of memories imported. */
  count: number;
  /** Number of edges recreated (from wikilinks in obsidian format). */
  edgesCreated: number;
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/** Events emitted by the MemoryManager. */
export type MemOSEvent =
  | "node:created"
  | "node:updated"
  | "node:deleted"
  | "edge:created"
  | "edge:deleted"
  | "link:auto"
  | "eviction"
  | "ttl:expired"
  | "embedding:queued"
  | "embedding:started"
  | "embedding:complete"
  | "embedding:failed"
  | "embedding:retry"
  | "consolidation:complete"
  | "trust:changed"
  | "validity:changed"
  | "facts:extracted"
  | "memory:reinforced"
  | "memory:superseded"
  | "contradiction:detected";

/** Event listener signature. */
export type MemOSEventListener = (data: unknown) => void;

// ---------------------------------------------------------------------------
// Memory consolidation
// ---------------------------------------------------------------------------

/** Options for {@link MemOS.dedupe}. */
export interface DedupeOptions {
  /** Cosine-similarity threshold above which two memories are merged. Default 0.92. */
  threshold?: number;
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** If true, do not delete or merge anything. Default false. */
  dryRun?: boolean;
  /** Cap on how many pairs to compare. Default 10_000. */
  maxPairs?: number;
}

/** A single merge performed by `dedupe()`. */
export interface DedupeMerge {
  /** The id of the surviving node. */
  kept: string;
  /** The ids of the nodes merged into the survivor and removed. */
  removed: string[];
  /** The reason this merge was selected. */
  reason: string;
  /** Mean cosine similarity across the cluster that was merged. */
  similarity: number;
}

/** Result returned by {@link MemOS.dedupe}. */
export interface DedupeResult {
  merges: DedupeMerge[];
  /** Number of distinct clusters that were detected. */
  clustersFound: number;
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.archive}. */
export interface ArchiveOptions {
  /** Move memories older than this many days. Default 90. */
  afterDays?: number;
  /** Cap on importance for archival. Default 0.3. */
  importanceBelow?: number;
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** If true, do not actually move anything. Default false. */
  dryRun?: boolean;
}

/** A single archive operation. */
export interface ArchiveMove {
  /** The id of the moved memory. */
  id: string;
  /** Reason it was archived (e.g. "stale_and_low_importance"). */
  reason: string;
}

/** Result returned by {@link MemOS.archive}. */
export interface ArchiveResult {
  moves: ArchiveMove[];
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.summarizeCluster}. */
export interface SummarizeClusterOptions {
  /** Namespace to cluster. Default "default". */
  namespace?: string;
  /** Minimum cluster size to summarize. Default 3. */
  minClusterSize?: number;
  /** Cosine-similarity threshold for cluster membership. Default 0.78. */
  threshold?: number;
  /** If true, do not actually create summary nodes. Default false. */
  dryRun?: boolean;
}

/** A cluster that was summarized. */
export interface ClusterSummary {
  /** The id of the newly-created summary node. Null when `dryRun: true`. */
  summaryId: string | null;
  /** The ids of the source nodes that the summary was derived from. */
  derivedFrom: string[];
  /** The generated summary text. */
  summary: string;
}

/** Result returned by {@link MemOS.summarizeCluster}. */
export interface SummarizeClusterResult {
  clusters: ClusterSummary[];
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.consolidate}. */
export interface ConsolidateOptions {
  /** Cosine threshold for dedupe. Default 0.92. */
  dedupeThreshold?: number;
  /** Move memories older than this many days. Default 90. */
  archiveAfterDays?: number;
  /** Cap on importance for archival. Default 0.3. */
  archiveImportanceBelow?: number;
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** If true, do not actually mutate anything. Default false. */
  dryRun?: boolean;
  /** Generate cluster summaries in addition to dedupe + archive. Default true. */
  summarize?: boolean;
  /** Minimum cluster size for summarization. Default 3. */
  minClusterSize?: number;
  /** Cosine threshold for cluster membership. Default 0.78. */
  clusterThreshold?: number;
  /**
   * Run decay-based forgetting (algorithmic forgetting with an exponential
   * recency half-life). Superseded memories are marked historical
   * (`validTo = now`) — never deleted — so they stay queryable via
   * `searchTemporal`. Default true.
   */
  decay?: boolean;
  /** Exponential half-life (days) for the recency term of the retention score. Default 60. */
  decayHalfLifeDays?: number;
  /** Retention scores below this supersede the memory. Default 0.2. */
  minRetentionScore?: number;
  /** Only memories created more than this many days ago are eligible. Default 60. */
  olderThanDays?: number;
}

/**
 * A single memory superseded by the decay-forgetting stage of
 * `consolidate()`.
 */
export interface DecaySuperseded {
  /** The superseded memory's id. */
  id: string;
  /** The retention score that fell below `minRetentionScore`. */
  score: number;
}

/** Options for {@link MemOS.forgetByDecay}. */
export interface DecayForgettingOptions {
  /** Only consider memories in this namespace. Default "default". */
  namespace?: string;
  /** Exponential half-life (days) for the recency term. Default 60. */
  halfLifeDays?: number;
  /** Retention scores below this supersede the memory. Default 0.2. */
  minScore?: number;
  /** Only memories untouched for this many days are eligible. Default 60. */
  olderThanDays?: number;
  /** If true, do not actually supersede anything. Default false. */
  dryRun?: boolean;
}

/** Result returned by {@link MemOS.forgetByDecay}. */
export interface DecayForgetResult {
  superseded: DecaySuperseded[];
  dryRun: boolean;
  durationMs: number;
}

/** Options for {@link MemOS.history}. */
export interface HistoryOptions {
  /** Minimum similarity for related versions. Default 0.8. */
  threshold?: number;
  /** Cap on related versions per direction. Default 10. */
  limit?: number;
}

/**
 * The full version timeline for one memory: the memory itself, the older
 * versions it replaced, the newer versions that replaced it, and any
 * consolidated notes derived from it. Supersession is inferred from
 * content similarity plus temporal-validity windows — superseded versions
 * are historical (`validTo` set), the live version is not.
 */
export interface MemoryHistory {
  node: MemoryNode;
  /** Older versions this memory replaced (oldest first). */
  supersedes: ScoredMemory[];
  /** Newer versions that replaced this memory (newest first). */
  supersededBy: ScoredMemory[];
  /** Notes (note pool) derived from this memory via `derived_from` edges. */
  derivedNotes: MemoryNode[];
  /** All graph edges touching this memory. */
  edges: MemoryEdge[];
}

/** Result returned by {@link MemOS.consolidate}. */
export interface ConsolidateResult {
  merges: DedupeMerge[];
  moves: ArchiveMove[];
  clusters: ClusterSummary[];
  /** Memories superseded by decay-based forgetting. */
  decayed: DecaySuperseded[];
  dryRun: boolean;
  durationMs: number;
}

// ---------------------------------------------------------------------------
// Fact extraction
// ---------------------------------------------------------------------------

/**
 * A single message in a conversation, used by `extractFacts`.
 */
export interface ConversationMessage {
  /** Speaker role: "user", "assistant", or "system". */
  role: "user" | "assistant" | "system";
  /** Message text content. */
  content: string;
  /** Optional speaker name for multi-user conversations. */
  speaker?: string;
}

/**
 * A candidate fact extracted from a conversation.
 */
export interface ExtractedFact {
  /** The extracted fact text. */
  content: string;
  /** Inferred memory type. */
  type: MemoryType;
  /** Confidence in [0, 1]. */
  confidence: number;
  /** Optional tags inferred from context. */
  tags: string[];
  /** Source of the fact — usually `user_input` or `agent_inferred`. */
  source: MemorySource;
}

/**
 * Options for {@link MemOS.extractFacts}.
 */
export interface ExtractFactsOptions {
  /**
   * If true, automatically store all extracted facts with confidence >=
   * `minConfidence`. Default false — returns candidates without storing.
   */
  autoStore?: boolean;
  /** Only auto-store facts with confidence >= this threshold. Default 0.6. */
  minConfidence?: number;
  /** Namespace to store facts in (when autoStore is true). */
  namespace?: string;
  /**
   * When true, skip facts that are near-duplicates of existing memories.
   * Default true.
   */
  dedupe?: boolean;
  /** Cosine similarity threshold for dedup. Default 0.85. */
  dedupeThreshold?: number;
}

/** Result returned by {@link MemOS.extractFacts}. */
export interface ExtractFactsResult {
  /** Extracted fact candidates. */
  facts: ExtractedFact[];
  /** IDs of stored nodes (when `autoStore` is true). */
  storedIds: string[];
  /** Number of facts skipped as near-duplicates. */
  duplicates: number;
}

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

/**
 * Detailed diagnostics snapshot returned by `memos.diagnostics()`.
 */
export interface DiagnosticsResult {
  /** Total number of stored memories. */
  totalNodes: number;
  /** Total number of edges. */
  totalEdges: number;
  /** Number of memories with embeddings. */
  nodesWithEmbeddings: number;
  /** Number of memories with temporal validity set. */
  nodesWithValidity: number;
  /** Number of historical (superseded) memories. */
  historicalNodes: number;
  /** Number of memories with a TTL. */
  nodesWithTTL: number;
  /** Number of expired memories pending sweep. */
  expiredNodes: number;
  /** Average importance across all nodes. */
  avgImportance: number;
  /** Average trust score across all nodes. */
  avgTrustScore: number;
  /** Breakdown of nodes by provenance source. */
  bySource: Record<string, number>;
  /** Breakdown of nodes by memory type. */
  byType: Record<string, number>;
  /** Breakdown of nodes by namespace. */
  byNamespace: Record<string, number>;
  /** Database file size in bytes. */
  dbSizeBytes: number;
  /** Embedding queue status, if configured. */
  embeddingQueue?: EmbeddingQueueStatus;
  /** Whether the storage adapter supports optional methods. */
  storageCapabilities: {
    peekNode: boolean;
    evictLeastImportant: boolean;
    saveEmbedding: boolean;
    getAllEmbeddings: boolean;
    setNodeNamespace: boolean;
  };
}
